x-defaults:
  docker:
    runtime_host: &docker-host /run/user/1000/podman/podman.sock

configs:
  api-config:
    content: |
      name: "Manager"
      standalone: false

      server:
        ip: 0.0.0.0
        port: 8080
        password: strongpassword123
        enable-reflection: true

      auth:
        jwt-expiration: 1h0m0s
        allow-signup: true
        bcrypt-cost: 12
        private-key: /etc/mc/jwt-priv.pem
        public-key: /etc/mc/jwt-pub.pem

      db:
        type: postgres
        url: postgres://postgres:docker@postgres:5432/mc
        max-conns: 10
        skip-preparation: false
        migrate: true

      cache:
        type: redis
        url: redis://redis:6379

      runner:
        enable: true
        id: "1411133174233402605"
        docker:
          prefix: mc
          network-name: mc_network
        data:
          data-dir: /data

services:
  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    command: ["--config", "/api-config.yaml"]
    environment:
      DOCKER_HOST: unix:///run/podman/podman.sock
    ports:
      - 8080:8080
    volumes:
      - ./data/data:/data
      - ./data/etc:/etc/mc
      - type: bind
        source: *docker-host
        target: /run/podman/podman.sock
    configs:
      - source: api-config
        target: /api-config.yaml
    links:
      - postgres
      - redis

  postgres:
    image: docker.io/library/postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/postgres:/var/lib/postgresql

  redis:
    image: docker.io/valkey/valkey:alpine
    restart: unless-stopped
    command: ["--save", "60", "1"]
    volumes:
      - ./data/redis:/data

networks:
  default:
    driver: bridge
